sudo: required
services:
  #necesitamos docker build preinstalado antes de correr nuestro build
  - docker
before_install:
  #SECRET para travis
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #este comando descarga sdk GoogleCloud      | este comando instala localmente una instania de GoogleCloud
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  #busca el directorio donde fue instalado GoogleCloud y modifica nuestro shell
  - source $HOME/google-cloud-sdk/path.bash.inc
  #instalar el comando kubectl dentro de nuestro ambiente de travis
  - gcloud components update kubectl
  # credenciales de autenticacion para google cloud
  - gcloud auth activate-service-account --key-file service-account.json 
